modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version} - ${minecraft_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''More Chest Variants adds new wood types to chests

Inspiration came from, More Crafting Tables -
https://www.curseforge.com/minecraft/mc-mods/more-crafting-tables-for-forge

[Make sure to set Mod Resources above Default]'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
